### ISSUE TITLE
Compile issue     analogSetCycles(1);

### ISSUE THREAD

**Issue by MichaelPNolan** [marcel-licence/esp32_usb_midi#4] opened 2021-07-05 12:49 UTC
Hi Marcel (hope that's ok for name),
      you owe nothing but as set up from downloading this library which I just initially want to test my USBhost midi - this analogue mux thing  - i don't have one. So I'll simplify this to get to where it works but fyi .. can't compile. Maybe you need to add another file to the respository here?

//In this function -- analogSetCycles(1);  error in arduino IDE - 'analogSetCycles' was not declared in this scope
```
void AdcMul_Init(void)
{
    for (int i = 0; i < ADC_INPUTS; i++)
    {
        adcChannelValue[i] = 0.5f;
    }

    memset(lastSendVal, 0xFF, sizeof(lastSendVal));

    analogReadResolution(10);
    analogSetAttenuation(ADC_11db);

    analogSetCycles(1);
    analogSetClockDiv(1);

    adcAttachPin(ADC_MUL_SIG_PIN);

    pinMode(ADC_MUL_S0_PIN, OUTPUT);
#if ADC_INPUTS > 2
    pinMode(ADC_MUL_S1_PIN, OUTPUT);
#endif
#if ADC_INPUTS > 4
    pinMode(ADC_MUL_S2_PIN, OUTPUT);
#endif
#if ADC_INPUTS > 8
    pinMode(ADC_MUL_S3_PIN, OUTPUT);
#endif
}

**Comment by marcel-licence** [comment] 2021-07-05 15:56
The issue is related to an old esp32 board library. I will update the adc code soon =)

**Comment by MichaelPNolan** [comment] 2021-07-05 18:17
Yes, its not present in esp32_basic_synth ... so now that's my basis to get some action. I'll also try to make the Esp32_a1s_audio board do something but I want to do the stand-alone dac way too.

**Comment by marcel-licence** [comment] 2021-10-21 21:33
Should be fixed now

**Closed by marcel-licence** 2021-10-21 21:33 UTC
